# Generated by Django 3.2.25 on 2025-06-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_street_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address1',
            new_name='default_street_address',
        ),
    ]
